name: Build MCL
description: Install MCL dependencies and build libmcl.a

runs:
  using: composite
  steps:
    - name: Install MCL build dependencies
      shell: bash
      run: sudo apt-get install -y libgmp-dev

    - name: Build MCL
      shell: bash
      run: make -C mcl -j$(nproc) MCL_FP_BIT=256 MCL_FR_BIT=256 lib/libmcl.a CC="zig cc" CXX="zig c++" CFLAGS_USER="-mevex512"
